
DROP TABLE IF EXISTS inspection_items;
DROP TABLE IF EXISTS inspections;
DROP TABLE IF EXISTS checklist_templates;
DROP TABLE IF EXISTS email_logs;
DROP TABLE IF EXISTS system_settings;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS departments;

CREATE TABLE departments (
    code TEXT PRIMARY KEY,
    name_th TEXT NOT NULL,
    name_en TEXT NOT NULL,
    description TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    phone TEXT,
    email TEXT UNIQUE NOT NULL,
    department TEXT NOT NULL,
    position TEXT NOT NULL,
    responsible_area TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'inspector',
    status TEXT NOT NULL DEFAULT 'approved',
    password_hash TEXT NOT NULL,
    notes TEXT,
    approved_by INTEGER,
    approved_at DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE checklist_templates (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    department_code TEXT NOT NULL,
    layer TEXT NOT NULL,
    category TEXT NOT NULL,
    subcategory TEXT,
    method TEXT,
    item_order INTEGER NOT NULL,
    question_th TEXT NOT NULL,
    question_en TEXT,
    row_in_excel INTEGER,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (department_code) REFERENCES departments(code)
);

CREATE TABLE inspections (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    department_code TEXT NOT NULL,
    year INTEGER NOT NULL,
    month INTEGER NOT NULL,
    layer TEXT NOT NULL,
    shift TEXT NOT NULL,
    mc_and_products TEXT NOT NULL,
    auditor_id INTEGER,
    auditor_name TEXT NOT NULL,
    audit_date TEXT NOT NULL,
    total_ok INTEGER DEFAULT 0,
    total_no INTEGER DEFAULT 0,
    total_na INTEGER DEFAULT 0,
    score_percent REAL DEFAULT 0.0,
    status TEXT DEFAULT 'completed',
    comments TEXT,
    previous_findings TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (department_code) REFERENCES departments(code)
);

CREATE TABLE inspection_items (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    inspection_id INTEGER NOT NULL,
    template_item_id INTEGER,
    layer TEXT NOT NULL,
    category TEXT NOT NULL,
    subcategory TEXT,
    question TEXT NOT NULL,
    result TEXT NOT NULL,
    finding_topic TEXT,
    severity TEXT,
    action_plan TEXT,
    responsible_person TEXT,
    due_date TEXT,
    image_url TEXT,
    image_key TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (inspection_id) REFERENCES inspections(id) ON DELETE CASCADE
);

CREATE TABLE email_logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    recipient_email TEXT NOT NULL,
    recipient_name TEXT,
    subject TEXT NOT NULL,
    body TEXT NOT NULL,
    type TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'sent',
    related_id INTEGER,
    error_message TEXT,
    sent_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE system_settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    description TEXT,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO departments (code, name_th, name_en, description) VALUES ('MOLD', 'แผนกฉีดขึ้นรูป (Molding / MM)', 'Molding / MM Department', 'Injection Molding and Maintenance');
INSERT INTO departments (code, name_th, name_en, description) VALUES ('FACILITY', 'แผนกสาธารณูปโภค (Facility)', 'Facility Department', 'Utilities, Safety, and Plant Infrastructure');
INSERT INTO departments (code, name_th, name_en, description) VALUES ('ASSY', 'แผนกประกอบ (Assembly)', 'Assembly Department', 'Component and Final Assembly Lines');
INSERT INTO departments (code, name_th, name_en, description) VALUES ('WH', 'แผนกคลังสินค้า (Warehouse)', 'Warehouse Department', 'Raw materials, Parts, and Finished Goods Storage');
INSERT INTO departments (code, name_th, name_en, description) VALUES ('QC', 'แผนกควบคุมคุณภาพ (QC)', 'Quality Control Department', 'Quality Assurance and Inspection');
INSERT INTO departments (code, name_th, name_en, description) VALUES ('STAMPING', 'แผนกปั๊มขึ้นรูป (Stamping)', 'Stamping Department', 'Metal Stamping and Pressing');
INSERT INTO departments (code, name_th, name_en, description) VALUES ('TOOL', 'แผนกแม่พิมพ์และเครื่องมือ (Tooling)', 'Tooling Department', 'Tool and Die Making and Repair');

INSERT INTO users (first_name, last_name, phone, email, department, position, responsible_area, role, status, password_hash, approved_at)
VALUES ('ผู้ดูแลระบบ', 'ส่วนกลาง (Admin)', '081-234-5678', 'admin@sbop.com', 'FACILITY', 'EHS Safety Manager', 'All Areas', 'admin', 'approved', '$2b$10$n.Amq4Ep/qxcwptS7uLmzurWRkhwuaTyGGdB0Wk6m24GPN2n8Kziu', CURRENT_TIMESTAMP);

INSERT INTO users (first_name, last_name, phone, email, department, position, responsible_area, role, status, password_hash, approved_at)
VALUES ('EHS', 'Administrator', '081-234-5678', 'ehsadmin@sbop.com', 'FACILITY', 'Safety Administrator', 'Plant Overall', 'admin', 'approved', '$2b$10$n.Amq4Ep/qxcwptS7uLmzurWRkhwuaTyGGdB0Wk6m24GPN2n8Kziu', CURRENT_TIMESTAMP);

INSERT INTO users (first_name, last_name, phone, email, department, position, responsible_area, role, status, password_hash, approved_at)
VALUES ('User', 'Tester', '089-999-8888', 'usertester@sbop.com', 'MOLD', 'Safety Inspector (Tester)', 'Zone A - Line 1', 'inspector', 'approved', '$2b$10$/IOn/AJYL5UgLHfGhe8stOg8/ERRY34JzBG7xyZYkyKM6TeLqp/tW', CURRENT_TIMESTAMP);

INSERT INTO users (first_name, last_name, phone, email, department, position, responsible_area, role, status, password_hash, approved_at)
VALUES ('Tester', 'Inspector', '089-999-8888', 'tester@sbop.com', 'ASSY', 'Inspector Tester', 'Assembly Line 1', 'inspector', 'approved', '$2b$10$/IOn/AJYL5UgLHfGhe8stOg8/ERRY34JzBG7xyZYkyKM6TeLqp/tW', CURRENT_TIMESTAMP);

INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('MOLD', 'Layer 3', 'SBOP (Systems Audit) Layer#3', '', 'Check', 1, 'การตรวจสอบในเรื่อง SBOP ของ Layer 2 ได้มีการดำเนินการแก้ไขอย่างถูกต้องและปัญหาที่พบได้รับการแก้ไขบนบอร์ด SBOP หรือไม่?', 12);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('MOLD', 'Layer 3', 'SBOP (Systems Audit) Layer#3', '', 'Check', 2, 'Supervisor,หัวหน้ากะและหัวหน้าฝ่ายบริหารในทุกระดับได้นำเรื่อง SBOP เข้าประชุมใน GO-Meeting และเป็นไปตามแผนที่วางไว้ หรือไม่ ?', 13);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('MOLD', 'Layer 2', 'SBOP (Systems Audit) Layer#2', '', 'Check', 1, 'การตรวจสอบในเรื่อง SBOP ของ Layer 1 ได้มีการดำเนินการแก้ไขอย่างถูกต้องและปัญหาที่พบได้รับการแก้ไขบนบอร์ด SBOP หรือไม่?', 17);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('MOLD', 'Layer 2', 'SBOP (Systems Audit) Layer#2', '', 'Check', 2, 'กิจกรรมด้านความปลอดภัยได้ถูกดำเนินการและตรวจสอบตามกำหนดเวลาหรือไม่ (BBS/CM/PM).', 18);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('MOLD', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 1, 'สังเกตพนักงานเป็นเวลา 60 วินาที', 22);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('MOLD', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 1, 'การเดินปฎิบัติงาน', 23);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('MOLD', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 2, 'การเข้าออก-พื้นที่ปฏิบัติงาน', 24);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('MOLD', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 3, 'ความสนใจกับงานที่กำลังปฏิบัติ', 25);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('MOLD', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 4, 'เทคนิคท่าทางการยกของเหมาะสม/ถูกต้อง', 26);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('MOLD', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 5, 'การก้ม/การบิด/การดึง/ตำแหน่งของร่างกาย', 27);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('MOLD', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 6, 'การยศาสตร์ (เช่น ท่าทาง)', 28);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('MOLD', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 7, 'ไม่เร่งรีบปฏิบัติงานจนเกินไป', 29);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('MOLD', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 1, 'มีความตระหนักถึงพื้นผิวร้อน', 31);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('MOLD', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 2, 'มีความตระหนักถึงจุดเคลื่อนไหวและส่วนหมุน', 32);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('MOLD', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 3, 'มีความตระหนักถึงจุดหนีบ', 33);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('MOLD', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 4, 'มีความตระหนักถึงวัตถุแหลมคมหรือบาด', 34);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('MOLD', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 5, 'มีความตระหนักถึงอันตรายไฟฟ้า', 35);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('MOLD', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 6, 'มีความตระหนักถึงระบบ Interlock/ปุ่มฉุกเฉิน', 36);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('MOLD', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 7, 'มีความตระหนักถึงการใช้อุปกรณ์ตามมาตรฐาน', 37);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('MOLD', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 8, 'มีความตระหนักถึงขั้นตอนการขนย้ายโมลอย่างถูกต้องและปลอดภัย', 38);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('MOLD', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 1, 'ใช้เครื่องมือถูกประเภทกับงาน', 40);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('MOLD', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 2, 'เครื่องมืออยู่ในสภาพที่ยอมรับได้', 41);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('MOLD', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 3, 'ใช้สวิตซ์มือหรือเท้าถูกต้องตามมาตรฐาน', 42);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('MOLD', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 4, 'การ์ดของเครื่องจักรหรืออุปกรณ์ต่างๆ ขณะทำงานอยู่ในตำแหน่งปลอดภัย', 43);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('MOLD', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 5, 'ไม่มีการรั่วไหลของลม', 44);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('MOLD', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 6, 'สายไฟอยู่ในสภาพปลอดภัยไม่ชารุดหรือเสียหาย', 45);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('MOLD', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 7, 'ใช้อุปกรณ์ล็อค และติดป้ายเตือน (LOTO)', 46);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('MOLD', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 8, 'ตรวจสอบความถูกต้องของท่อ TCU และ ข้อต่อก่อนทำงาน', 47);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('MOLD', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 9, 'Airgun ตรงตามมาตรฐาน และสภาพพร้อมใช้งานไม่ชำรุด', 48);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('MOLD', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 9, 'รถ  Electric Stacker หรือ Powered Hand Pallet มีการตรวจเช็ค สภาพพร้อมใช้งาน', 49);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('MOLD', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 10, 'เครื่องเย็บมีสภาพสมบูรณ์ พร้อมใช้งาน', 50);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('MOLD', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 11, 'รถเข็น มีสภาพสมบูรณ์ และจัดเก็บในพื้นที่ที่กำหนด ไม่วางพิงกับเรื่องจักร หรืออุปกรณ์อื่นๆ', 51);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('MOLD', 'Layer 1', 'II. สภาพแวดล้อมการทำงาน -  การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 1, 'พื้นที่ปฏิบัติงานไม่มีของวางบนพื้น (5S+1)', 54);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('MOLD', 'Layer 1', 'II. สภาพแวดล้อมการทำงาน -  การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 2, 'การกำจัดของเสียคัดแยกถูกประเภท (5S+1)', 55);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('MOLD', 'Layer 1', 'II. สภาพแวดล้อมการทำงาน -  การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 3, 'ทางเดินเปิดโล่งไม่สิ่งของกีดขวาง (5S+1)', 56);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('MOLD', 'Layer 1', 'II. สภาพแวดล้อมการทำงาน -  การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 4, 'ทางหนีไฟไม่มีสิ่งของวาง ขัดขวางการอพยพ', 57);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('MOLD', 'Layer 1', 'II. สภาพแวดล้อมการทำงาน -  การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 5, 'อุปกรณ์ป้องกันอัคคีภัย ไม่มีสิ่งของวางสามารถเข้าถึงได้กรณีเกิดเหตุฉุกเฉิน', 58);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('MOLD', 'Layer 1', 'III. PPE', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 1, 'มาตรฐานที่กำหนด รองเท้า, แว่นตา,หมวกนิรภัย', 59);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('MOLD', 'Layer 1', 'III. PPE', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 2, 'สวมถุงมือกันสารเคมี, ถุงมือกันความร้อน,ถุงมือกันบาด', 60);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('MOLD', 'Layer 1', 'III. PPE', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 3, 'สวมอุปกรณ์ป้องกันการหายใจ เช่นหน้ากากป้องกันฝุ่น  หรือไอสารเคมี', 61);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('MOLD', 'Layer 1', 'III. PPE', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 4, 'สวมอุปกรณ์ PPE สำหรับขั้นตอน การทำงานกับพลาสติกเหลวร้อน ทั้งหน้าแม่พิมพ์ และ บริเวณ Nozzle', 62);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('MOLD', 'Layer 1', 'IIII.  High risk process', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 1, 'มีการใช้ แคลมป์ล๊อค plate ขณะซ่อมแม่พิมพ์หรือไม่', 64);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('MOLD', 'Layer 1', 'IIII.  High risk process', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 2, 'ตะขอเกี่ยวแม่พิมพ์มี cover และอยู่ในสภาพพร้อมใช้งานหรือไม่', 65);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('MOLD', 'Layer 1', 'IIII.  High risk process', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 3, 'เป่าชิ้นงานภายในตู้หลังจากล้างที่เครื่อง ultrasonic หรือไม่', 66);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('MOLD', 'Layer 1', 'IIII.  High risk process', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 4, 'เครื่องตรวจจับก๊าซอาร์กอนรั่ว ทำงานปกติหรือไม่', 67);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('MOLD', 'Layer 1', 'IIII.  High risk process', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 5, 'ไม่ใช้ Electric Stacker (Jumbo) ขนาด 1.2 ตัน ขนย้ายโมลเข้ามายังพื้นที่ในโซนเครื่องจักร', 68);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('MOLD', 'Layer 1', 'IIII.  High risk process', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 6, 'การ์ดของเครื่องจักรอยู่ในสภาพพร้อมใช้งาน ไม่แตกหรือชำรุด', 69);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('MOLD', 'Layer 1', 'IIII.  High risk process', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 7, 'สวมถุงมือ และ Ear Muff ขณะใช้ cold jet', 70);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('FACILITY', 'Layer 3', 'SBOP (Systems Audit) Layer#3', '', 'Check', 1, 'การตรวจสอบในเรื่อง SBOP ของ Layer 2 ได้มีการดำเนินการแก้ไขอย่างถูกต้องและปัญหาที่พบได้รับการแก้ไขบนบอร์ด SBOP หรือไม่?', 12);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('FACILITY', 'Layer 3', 'SBOP (Systems Audit) Layer#3', '', 'Check', 2, 'Supervisor,หัวหน้ากะและหัวหน้าฝ่ายบริหารในทุกระดับได้นำเรื่อง SBOP เข้าประชุมใน GO-Meeting และเป็นไปตามแผนที่วางไว้ หรือไม่ ?', 13);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('FACILITY', 'Layer 2', 'SBOP (Systems Audit) Layer#2', '', 'Check', 1, 'การตรวจสอบในเรื่อง SBOP ของ Layer 1 ได้มีการดำเนินการแก้ไขอย่างถูกต้องและปัญหาที่พบได้รับการแก้ไขบนบอร์ด SBOP หรือไม่?', 17);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('FACILITY', 'Layer 2', 'SBOP (Systems Audit) Layer#2', '', 'Check', 2, 'กิจกรรมด้านความปลอดภัยได้ถูกดำเนินการและตรวจสอบตามกำหนดเวลาหรือไม่ (BBS/CM/PM).', 18);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('FACILITY', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 1, 'สังเกตพนักงานเป็นเวลา 60 วินาที', 22);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('FACILITY', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 1, 'การเดินปฏิบัติงาน', 23);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('FACILITY', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 2, 'การเข้าออก-พื้นที่ปฏิบัติงาน', 24);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('FACILITY', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 3, 'ความสนใจกับงานที่กำลังปฏิบัติ', 25);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('FACILITY', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 4, 'เทคนิคท่าทางการยกของเหมาะสม/ถูกต้อง', 26);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('FACILITY', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 5, 'การก้ม/การบิด/การดึง/ตำแหน่งของร่างกาย', 27);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('FACILITY', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 6, 'การยศาสตร์ (เช่น ท่าทาง)', 28);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('FACILITY', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 7, 'ไม่เร่งรีบปฏิบัติงานจนเกินไป', 29);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('FACILITY', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 1, 'มีความตระหนักถึงพื้นผิวร้อน', 31);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('FACILITY', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 2, 'มีความตระหนักถึงจุดเคลื่อนไหวและส่วนหมุน', 32);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('FACILITY', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 3, 'มีความตระหนักถึงจุดหนีบ', 33);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('FACILITY', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 4, 'มีความตระหนักถึงวัตถุแหลมคมหรือบาด', 34);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('FACILITY', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 5, 'มีความตระหนักถึงอันตรายไฟฟ้า', 35);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('FACILITY', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 6, 'มีความตระหนักถึงระบบ Interlock/ปุ่มฉุกเฉิน', 36);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('FACILITY', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 7, 'มีความตระหนักถึงการใช้อุปกรณ์ตามมาตรฐาน', 37);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('FACILITY', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 8, 'มีความตระหนักถึงการคัดแยกขยะที่ถูกต้อง', 38);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('FACILITY', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 1, 'ใช้เครื่องมือถูกประเภทกับงาน', 40);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('FACILITY', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 2, 'เครื่องมืออยู่ในสภาพที่ยอมรับได้', 41);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('FACILITY', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 3, 'ใช้สวิตซ์มือหรือเท้าถูกต้องตามมาตรฐาน', 42);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('FACILITY', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 4, 'การ์ดของเครื่องจักรหรืออุปกรณ์ต่างๆ ขณะทำงานอยู่ในตำแหน่งปลอดภัย', 43);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('FACILITY', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 5, 'ไม่มีการรั่วไหลของลม', 44);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('FACILITY', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 6, 'สายไฟอยู่ในสภาพปลอดภัยไม่ชารุดหรือเสียหาย', 45);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('FACILITY', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 7, 'ใช้อุปกรณ์ล็อค และติดป้ายเตือน (LOTO)', 46);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('FACILITY', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 8, 'ปิดการ์ดเครื่องจักรทุกครั้งที่มีการ Repair หรือ PM', 47);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('FACILITY', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 9, 'บันไดสภาพพร้อมใช้งาน และมีการตรวจเช็คก่อนใช้งาน', 48);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('FACILITY', 'Layer 1', 'II. สภาพแวดล้อมการทำงาน -  การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 1, 'พื้นที่ปฏิบัติงานไม่มีของวางบนพื้น (5S+1)', 50);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('FACILITY', 'Layer 1', 'II. สภาพแวดล้อมการทำงาน -  การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 2, 'การกำจัดของเสียคัดแยกถูกประเภท (5S+1)', 51);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('FACILITY', 'Layer 1', 'II. สภาพแวดล้อมการทำงาน -  การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 3, 'ทางเดินเปิดโล่งไม่สิ่งของกีดขวาง (5S+1)', 52);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('FACILITY', 'Layer 1', 'II. สภาพแวดล้อมการทำงาน -  การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 4, 'ทางหนีไฟไม่มีสิ่งของวาง ขัดขวางการอพยพ', 53);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('FACILITY', 'Layer 1', 'II. สภาพแวดล้อมการทำงาน -  การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 5, 'อุปกรณ์ป้องกันอัคคีภัย ไม่มีสิ่งของกีดขวางสามารถเข้าถึงได้กรณีเกิดเหตุฉุกเฉิน', 54);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('FACILITY', 'Layer 1', 'III. PPE', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 1, 'มาตรฐานที่กำหนด รองเท้า, แว่นตา,หมวกนิรภัย', 55);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('FACILITY', 'Layer 1', 'III. PPE', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 2, 'สวมถุงมือกันสารเคมี, ถุงมือกันความร้อน,ถุงมือกันบาด', 56);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('FACILITY', 'Layer 1', 'III. PPE', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 3, 'สวมอุปกรณ์ป้องกันการหายใจ เช่นหน้ากากป้องกันฝุ่น  หรือไอสารเคมี', 57);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('FACILITY', 'Layer 1', 'IIII.  High risk process', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 1, 'ผู้รับเหมาผ่านการอบรม พร้อมสำหรับทำงานบนที่สูง (กรณีมีผู้รับเหมาปฏิบัติงาน)', 61);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('FACILITY', 'Layer 1', 'IIII.  High risk process', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 2, 'ใช้อุปกรณ์กันตกสำหรับงานที่สูง และสภาพพร้อมใช้งาน', 62);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('ASSY', 'Layer 3', 'SBOP (Systems Audit) Layer#3', '', 'Check', 1, 'การตรวจสอบในเรื่อง SBOP ของ Layer 2 ได้มีการดำเนินการแก้ไขอย่างถูกต้องและปัญหาที่พบได้รับการแก้ไขบนบอร์ด SBOP หรือไม่?', 12);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('ASSY', 'Layer 3', 'SBOP (Systems Audit) Layer#3', '', 'Check', 2, 'Supervisor,หัวหน้ากะและหัวหน้าฝ่ายบริหารในทุกระดับได้นำเรื่อง SBOP เข้าประชุมใน GO-Meeting และเป็นไปตามแผนที่วางไว้ หรือไม่ ?', 13);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('ASSY', 'Layer 2', 'SBOP (Systems Audit) Layer#2', '', 'Check', 1, 'การตรวจสอบในเรื่อง SBOP ของ Layer 1 ได้มีการดำเนินการแก้ไขอย่างถูกต้องและปัญหาที่พบได้รับการแก้ไขบนบอร์ด SBOP หรือไม่?', 17);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('ASSY', 'Layer 2', 'SBOP (Systems Audit) Layer#2', '', 'Check', 2, 'กิจกรรมด้านความปลอดภัยได้ถูกดำเนินการและตรวจสอบตามกำหนดเวลาหรือไม่ (BBS/CM/PM).', 18);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('ASSY', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 1, 'สังเกตพนักงานเป็นเวลา 60 วินาที', 22);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('ASSY', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 1, 'การเดินปฏิบัติงาน', 23);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('ASSY', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 2, 'การเข้าออก-พื้นที่ปฏิบัติงาน', 24);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('ASSY', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 3, 'ความสนใจกับงานที่กำลังปฏิบัติ', 25);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('ASSY', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 4, 'เทคนิคท่าทางการยกของเหมาะสม/ถูกต้อง', 26);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('ASSY', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 5, 'การก้ม/การบิด/การดึง/ตำแหน่งของร่างกาย', 27);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('ASSY', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 6, 'การยศาสตร์ (เช่น ท่าทาง)', 28);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('ASSY', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 7, 'ไม่เร่งรีบปฏิบัติงานจนเกินไป', 29);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('ASSY', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 1, 'มีความตระหนักถึงพื้นผิวร้อน', 31);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('ASSY', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 2, 'มีความตระหนักถึงจุดเคลื่อนไหวและส่วนหมุน', 32);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('ASSY', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 3, 'มีความตระหนักถึงจุดหนีบ', 33);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('ASSY', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 4, 'มีความตระหนักถึงวัตถุแหลมคมหรือบาด', 34);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('ASSY', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 5, 'มีความตระหนักถึงอันตรายไฟฟ้า', 35);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('ASSY', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 6, 'มีความตระหนักถึงระบบ Interlock/ปุ่มฉุกเฉิน', 36);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('ASSY', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 7, 'มีความตระหนักถึงการใช้อุปกรณ์ตามมาตรฐาน', 37);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('ASSY', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 1, 'ใช้เครื่องมือถูกประเภทกับงาน', 39);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('ASSY', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 2, 'เครื่องมืออยู่ในสภาพที่ยอมรับได้', 40);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('ASSY', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 3, 'ใช้สวิตซ์มือหรือเท้าถูกต้องตามมาตรฐาน', 41);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('ASSY', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 4, 'การ์ดของเครื่องจักรหรืออุปกรณ์ต่างๆ ขณะทำงานอยู่ในตำแหน่งปลอดภัย', 42);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('ASSY', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 5, 'ไม่มีการรั่วไหลของลม', 43);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('ASSY', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 6, 'สายไฟอยู่ในสภาพปลอดภัยไม่ชารุดหรือเสียหาย', 44);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('ASSY', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 7, 'ใช้อุปกรณ์ล็อค และติดป้ายเตือน (LOTO)', 45);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('ASSY', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 8, 'Airgun ตรงตามมาตรฐาน และสภาพพร้อมใช้งานไม่ชำรุด', 46);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('ASSY', 'Layer 1', 'II. สภาพแวดล้อมการทำงาน -  การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 1, 'พื้นที่ปฏิบัติงานไม่มีของวางบนพื้น (5S+1)', 48);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('ASSY', 'Layer 1', 'II. สภาพแวดล้อมการทำงาน -  การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 2, 'การกำจัดของเสียคัดแยกถูกประเภท (5S+1)', 49);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('ASSY', 'Layer 1', 'II. สภาพแวดล้อมการทำงาน -  การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 3, 'ทางเดินเปิดโล่งไม่สิ่งของกีดขวาง (5S+1)', 50);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('ASSY', 'Layer 1', 'II. สภาพแวดล้อมการทำงาน -  การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 4, 'ทางหนีไฟไม่มีสิ่งของวาง ขัดขวางการอพยพ', 51);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('ASSY', 'Layer 1', 'II. สภาพแวดล้อมการทำงาน -  การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 5, 'อุปกรณ์ป้องกันอัคคีภัยภายในพื้นที่ ไม่มีสิ่งของกีดขวาง', 52);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('ASSY', 'Layer 1', 'III. PPE', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 1, 'มาตรฐานที่กำหนด รองเท้า, แว่นตา', 53);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('ASSY', 'Layer 1', 'III. PPE', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 2, 'สวมถุงมือกันสารเคมี, ถุงมือกันความร้อน,ถุงมือกันบาด', 54);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('ASSY', 'Layer 1', 'III. PPE', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 3, 'สวมอุปกรณ์ป้องกันการหายใจ เช่นหน้ากากป้องกันฝุ่น  หรือไอสารเคมี', 55);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('WH', 'Layer 3', 'SBOP (Systems Audit) Layer#3', '', 'Check', 1, 'การตรวจสอบในเรื่อง SBOP ของ Layer 2 ได้มีการดำเนินการแก้ไขอย่างถูกต้องและปัญหาที่พบได้รับการแก้ไขบนบอร์ด SBOP หรือไม่?', 12);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('WH', 'Layer 3', 'SBOP (Systems Audit) Layer#3', '', 'Check', 2, 'Supervisor,หัวหน้ากะและหัวหน้าฝ่ายบริหารในทุกระดับได้นำเรื่อง SBOP เข้าประชุมใน GO-Meeting และเป็นไปตามแผนที่วางไว้ หรือไม่ ?', 13);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('WH', 'Layer 2', 'SBOP (Systems Audit) Layer#2', '', 'Check', 1, 'การตรวจสอบในเรื่อง SBOP ของ Layer 1 ได้มีการดำเนินการแก้ไขอย่างถูกต้องและปัญหาที่พบได้รับการแก้ไขบนบอร์ด SBOP หรือไม่?', 17);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('WH', 'Layer 2', 'SBOP (Systems Audit) Layer#2', '', 'Check', 2, 'กิจกรรมด้านความปลอดภัยได้ถูกดำเนินการและตรวจสอบตามกำหนดเวลาหรือไม่ (BBS/CM/PM).', 18);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('WH', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 1, 'สังเกตพนักงานเป็นเวลา 60 วินาที', 22);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('WH', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 1, 'การเดินปฏิบัติงาน', 23);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('WH', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 2, 'การเข้าออก-พื้นที่ปฏิบัติงาน', 24);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('WH', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 3, 'ความสนใจกับงานที่กำลังปฏิบัติ', 25);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('WH', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 4, 'เทคนิคท่าทางการยกของเหมาะสม/ถูกต้อง', 26);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('WH', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 5, 'การก้ม/การบิด/การดึง/ตำแหน่งของร่างกาย', 27);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('WH', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 6, 'การยศาสตร์ (เช่น ท่าทาง)', 28);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('WH', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 7, 'ไม่เร่งรีบปฏิบัติงานจนเกินไป', 29);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('WH', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 1, 'มีความตระหนักถึงพื้นผิวร้อน', 31);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('WH', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 2, 'มีความตระหนักถึงจุดเคลื่อนไหวและส่วนหมุน', 32);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('WH', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 3, 'มีความตระหนักถึงจุดหนีบ', 33);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('WH', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 4, 'มีความตระหนักถึงวัตถุแหลมคมหรือบาด', 34);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('WH', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 5, 'มีความตระหนักถึงอันตรายไฟฟ้า', 35);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('WH', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 6, 'มีความตระหนักถึงระบบ Interlock/ปุ่มฉุกเฉิน', 36);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('WH', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 7, 'มีความตระหนักถึงการใช้อุปกรณ์ตามมาตรฐาน', 37);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('WH', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 8, 'มีความตระหนักถึงอันตรายจากสิ่งของตกจากที่สูง', 38);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('WH', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 9, 'มีความตระหนักถึงความปลอดภัยในการขับขี่ Fork lift', 39);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('WH', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 1, 'ใช้เครื่องมือถูกประเภทกับงาน', 41);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('WH', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 2, 'เครื่องมืออยู่ในสภาพที่ยอมรับได้', 42);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('WH', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 3, 'ใช้สวิตซ์มือหรือเท้าถูกต้องตามมาตรฐาน', 43);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('WH', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 4, 'การ์ดของเครื่องจักรหรืออุปกรณ์ต่างๆ ขณะทำงานอยู่ในตำแหน่งปลอดภัย', 44);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('WH', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 5, 'ไม่มีการรั่วไหลของลม', 45);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('WH', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 6, 'สายไฟอยู่ในสภาพปลอดภัยไม่ชารุดหรือเสียหาย', 46);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('WH', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 7, 'ใช้อุปกรณ์ล็อค และติดป้ายเตือน (LOTO)', 47);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('WH', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 8, 'พาเลทสภาพพร้อมใช้งาน ไม่แตกชำรุด', 48);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('WH', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 9, 'Fork lift สภาพพร้อมใช้งาน มีการตรวจเช็คก่อนใช้งาน ถอดกุญแจทุกครั้งหลังจากการใช้งาน', 49);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('WH', 'Layer 1', 'II. สภาพแวดล้อมการทำงาน -  การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 1, 'พื้นที่ปฏิบัติงานไม่มีของวางบนพื้น (5S+1)', 51);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('WH', 'Layer 1', 'II. สภาพแวดล้อมการทำงาน -  การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 2, 'การกำจัดของเสียคัดแยกถูกประเภท (5S+1)', 52);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('WH', 'Layer 1', 'II. สภาพแวดล้อมการทำงาน -  การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 3, 'ทางเดินเปิดโล่งไม่สิ่งของกีดขวาง (5S+1)', 53);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('WH', 'Layer 1', 'II. สภาพแวดล้อมการทำงาน -  การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 4, 'ทางหนีไฟไม่มีสิ่งของวาง ขัดขวางการอพยพ', 54);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('WH', 'Layer 1', 'III. PPE', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 1, 'มาตรฐานที่กำหนด รองเท้า, แว่นตา', 55);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('WH', 'Layer 1', 'III. PPE', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 2, 'สวมถุงมือกันสารเคมี, ถุงมือกันความร้อน,ถุงมือกันบาด', 56);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('WH', 'Layer 1', 'III. PPE', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 3, 'สวมอุปกรณ์ป้องกันการหายใจ เช่นหน้ากากป้องกันฝุ่น  หรือไอสารเคมี', 57);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('WH', 'Layer 1', 'III. PPE', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 4, 'สวมหมวกแข็งเมื่อปฏิบัติงานอยู่ในพื้นที่ในRack', 58);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('WH', 'Layer 1', 'III. PPE', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 5, 'สวมถุงมือผ้าทุกครั้งที่มีการตัดสายรัดสแตนเลส', 59);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('WH', 'Layer 1', 'IIII.  High risk process', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 7, 'ไม่นำรถ Fork Lift เสากระโดงงาสูง Serial number MHB4279H เข้าไปยังพื้นที่ห้องควบคุม', 67);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('WH', 'Layer 1', 'IIII.  High risk process', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 8, 'Set limit max การยกงาของรถโฟรค์ลิฟ กำหนดมาตรฐานการตักงานจากที่สูง', 69);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('QC', 'Layer 3', 'SBOP (Systems Audit) Layer#3', '', 'Check', 1, 'การตรวจสอบในเรื่อง SBOP ของ Layer 2 ได้มีการดำเนินการแก้ไขอย่างถูกต้องและปัญหาที่พบได้รับการแก้ไขบนบอร์ด SBOP หรือไม่?', 12);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('QC', 'Layer 3', 'SBOP (Systems Audit) Layer#3', '', 'Check', 2, 'Supervisor,หัวหน้ากะและหัวหน้าฝ่ายบริหารในทุกระดับได้นำเรื่อง SBOP เข้าประชุมใน GO-Meeting และเป็นไปตามแผนที่วางไว้ หรือไม่ ?', 13);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('QC', 'Layer 2', 'SBOP (Systems Audit) Layer#2', '', 'Check', 1, 'การตรวจสอบในเรื่อง SBOP ของ Layer 1 ได้มีการดำเนินการแก้ไขอย่างถูกต้องและปัญหาที่พบได้รับการแก้ไขบนบอร์ด SBOP หรือไม่?', 17);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('QC', 'Layer 2', 'SBOP (Systems Audit) Layer#2', '', 'Check', 2, 'กิจกรรมด้านความปลอดภัยได้ถูกดำเนินการและตรวจสอบตามกำหนดเวลาหรือไม่ (BBS/CM/PM).', 18);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('QC', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 1, 'สังเกตพนักงานเป็นเวลา 60 วินาที', 22);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('QC', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 1, 'การเดินปฏิบัติงาน', 23);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('QC', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 2, 'การเข้าออก-พื้นที่ปฏิบัติงาน', 24);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('QC', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 3, 'ความสนใจกับงานที่กำลังปฏิบัติ', 25);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('QC', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 4, 'เทคนิคท่าทางการยกของเหมาะสม/ถูกต้อง', 26);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('QC', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 5, 'การก้ม/การบิด/การดึง/ตำแหน่งของร่างกาย', 27);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('QC', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 6, 'การยศาสตร์ (เช่น ท่าทาง)', 28);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('QC', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 7, 'ไม่เร่งรีบปฏิบัติงานจนเกินไป', 29);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('QC', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 1, 'มีความตระหนักถึงพื้นผิวร้อน', 31);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('QC', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 2, 'มีความตระหนักถึงจุดเคลื่อนไหวและส่วนหมุน', 32);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('QC', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 3, 'มีความตระหนักถึงจุดหนีบ', 33);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('QC', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 4, 'มีความตระหนักถึงวัตถุแหลมคมหรือบาด', 34);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('QC', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 5, 'มีความตระหนักถึงอันตรายไฟฟ้า', 35);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('QC', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 6, 'มีความตระหนักถึงระบบ Interlock/ปุ่มฉุกเฉิน', 36);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('QC', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 7, 'มีความตระหนักถึงการใช้อุปกรณ์ตามมาตรฐาน', 37);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('QC', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 1, 'ใช้เครื่องมือถูกประเภทกับงาน', 39);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('QC', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 2, 'เครื่องมืออยู่ในสภาพที่ยอมรับได้', 40);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('QC', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 3, 'ใช้สวิตซ์มือหรือเท้าถูกต้องตามมาตรฐาน', 41);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('QC', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 4, 'การ์ดของเครื่องจักรหรืออุปกรณ์ต่างๆ ขณะทำงานอยู่ในตำแหน่งปลอดภัย', 42);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('QC', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 5, 'ไม่มีการรั่วไหลของลม', 43);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('QC', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 6, 'สายไฟอยู่ในสภาพปลอดภัยไม่ชารุดหรือเสียหาย', 44);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('QC', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 7, 'ใช้อุปกรณ์ล็อค และติดป้ายเตือน (LOTO)', 45);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('QC', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 8, 'ครื่องวัดแรงดึงมีการใช้การ์ดก่อนการทดสอบ', 46);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('QC', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 9, 'มีการใช้การ์ดหรืออุปกรณ์ป้องกันในการตัด', 47);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('QC', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 10, 'การ์ดของเครื่องจักรอยู่ในสภาพพร้อมใช้งาน ไม่แตกหรือชำรุด', 48);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('QC', 'Layer 1', 'II. สภาพแวดล้อมการทำงาน -  การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 1, 'พื้นที่ปฏิบัติงานไม่มีของวางบนพื้น (5S+1)', 50);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('QC', 'Layer 1', 'II. สภาพแวดล้อมการทำงาน -  การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 2, 'การกำจัดของเสียคัดแยกถูกประเภท (5S+1)', 51);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('QC', 'Layer 1', 'II. สภาพแวดล้อมการทำงาน -  การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 3, 'ทางเดินเปิดโล่งไม่สิ่งของกีดขวาง (5S+1)', 52);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('QC', 'Layer 1', 'II. สภาพแวดล้อมการทำงาน -  การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 4, 'ทางหนีไฟไม่มีสิ่งของวาง ขัดขวางการอพยพ', 53);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('QC', 'Layer 1', 'II. สภาพแวดล้อมการทำงาน -  การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 5, 'อุปกรณ์ป้องกันอัคคีภัย ไม่มีสิ่งของกีดขวางสามารถเข้าถึงได้กรณีเกิดเหตุฉุกเฉิน', 54);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('QC', 'Layer 1', 'III. PPE', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 1, 'มาตรฐานที่กำหนด รองเท้า, แว่นตา', 55);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('QC', 'Layer 1', 'III. PPE', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 2, 'สวมถุงมือกันสารเคมี, ถุงมือกันความร้อน,ถุงมือกันบาด', 56);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('QC', 'Layer 1', 'III. PPE', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 3, 'สวมอุปกรณ์ป้องกันการหายใจ เช่นหน้ากากป้องกันฝุ่น  หรือไอสารเคมี', 57);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('STAMPING', 'Layer 3', 'SBOP (Systems Audit) Layer#3', '', 'Check', 1, 'การตรวจสอบในเรื่อง SBOP ของ Layer 2 ได้มีการดำเนินการแก้ไขอย่างถูกต้องและปัญหาที่พบได้รับการแก้ไขบนบอร์ด SBOP หรือไม่?', 12);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('STAMPING', 'Layer 3', 'SBOP (Systems Audit) Layer#3', '', 'Check', 2, 'Supervisor,หัวหน้ากะและหัวหน้าฝ่ายบริหารในทุกระดับได้นำเรื่อง SBOP เข้าประชุมใน GO-Meeting และเป็นไปตามแผนที่วางไว้ หรือไม่ ?', 13);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('STAMPING', 'Layer 2', 'SBOP (Systems Audit) Layer#2', '', 'Check', 1, 'การตรวจสอบในเรื่อง SBOP ของ Layer 1 ได้มีการดำเนินการแก้ไขอย่างถูกต้องและปัญหาที่พบได้รับการแก้ไขบนบอร์ด SBOP หรือไม่?', 17);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('STAMPING', 'Layer 2', 'SBOP (Systems Audit) Layer#2', '', 'Check', 2, 'กิจกรรมด้านความปลอดภัยได้ถูกดำเนินการและตรวจสอบตามกำหนดเวลาหรือไม่ (BBS/CM/PM).', 18);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('STAMPING', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 1, 'สังเกตพนักงานเป็นเวลา 60 วินาที', 22);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('STAMPING', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 1, 'การเดินปฏิบัติงาน', 23);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('STAMPING', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 2, 'การเข้าออก-พื้นที่ปฏิบัติงาน', 24);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('STAMPING', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 3, 'ความสนใจกับงานที่กำลังปฏิบัติ', 25);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('STAMPING', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 4, 'เทคนิคท่าทางการยกของเหมาะสม/ถูกต้อง', 26);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('STAMPING', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 5, 'การก้ม/การบิด/การดึง/ตำแหน่งของร่างกาย', 27);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('STAMPING', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 6, 'การยศาสตร์ (เช่น ท่าทาง)', 28);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('STAMPING', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 1, 'มีความตระหนักถึงพื้นผิวร้อน', 30);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('STAMPING', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 2, 'มีความตระหนักถึงจุดเคลื่อนไหวและส่วนหมุน', 31);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('STAMPING', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 3, 'มีความตระหนักถึงจุดหนีบ', 32);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('STAMPING', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 4, 'มีความตระหนักถึงวัตถุแหลมคมหรือบาด', 33);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('STAMPING', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 5, 'มีความตระหนักถึงอันตรายไฟฟ้า', 34);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('STAMPING', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 6, 'มีความตระหนักถึงระบบ Interlock/ปุ่มฉุกเฉิน', 35);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('STAMPING', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 7, 'มีความตระหนักถึงการใช้อุปกรณ์ตามมาตรฐาน', 36);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('STAMPING', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 8, 'มีความตระหนักถึงการใช้ Hand lift,Lifter', 37);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('STAMPING', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 1, 'ใช้เครื่องมือถูกประเภทกับงาน', 39);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('STAMPING', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 2, 'เครื่องมืออยู่ในสภาพที่ยอมรับได้', 40);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('STAMPING', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 3, 'ใช้สวิตซ์มือหรือเท้าถูกต้องตามมาตรฐาน', 41);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('STAMPING', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 4, 'การ์ดของเครื่องจักรหรืออุปกรณ์ต่างๆ ขณะทำงานอยู่ในตำแหน่งปลอดภัย', 42);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('STAMPING', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 5, 'ไม่มีการรั่วไหลของลม', 43);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('STAMPING', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 6, 'สายไฟอยู่ในสภาพปลอดภัยไม่ชารุดหรือเสียหาย', 44);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('STAMPING', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 7, 'ใช้อุปกรณ์ล็อค และติดป้ายเตือน (LOTO)', 45);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('STAMPING', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 8, 'เครื่องมือสำหรับตัด,กรรไกร สภาพพร้อมใช้งาน', 46);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('STAMPING', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 9, 'Hand lift,Lifter ไม่ชำรุดพร้อมใช้งานอยู่เสมอ', 47);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('STAMPING', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 10, 'Electric Stacker สภาพพร้อมใช้งาน ถอดกุญแจทุกครั้งหลังจากการใช้งาน', 48);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('STAMPING', 'Layer 1', 'II. สภาพแวดล้อมการทำงาน -  การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 1, 'พื้นที่ปฏิบัติงานไม่มีของวางบนพื้น (5S+1)', 50);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('STAMPING', 'Layer 1', 'II. สภาพแวดล้อมการทำงาน -  การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 2, 'การกำจัดของเสียคัดแยกถูกประเภท (5S+1)', 51);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('STAMPING', 'Layer 1', 'II. สภาพแวดล้อมการทำงาน -  การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 3, 'ทางเดินเปิดโล่งไม่สิ่งของกีดขวาง (5S+1)', 52);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('STAMPING', 'Layer 1', 'II. สภาพแวดล้อมการทำงาน -  การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 4, 'ทางหนีไฟไม่มีสิ่งของวาง ขัดขวางการอพยพ', 53);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('STAMPING', 'Layer 1', 'II. สภาพแวดล้อมการทำงาน -  การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 5, 'อุปกรณ์ป้องกันอัคคีภัย ไม่มีสิ่งของกีดขวางสามารถเข้าถึงได้กรณีเกิดเหตุฉุกเฉิน', 54);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('STAMPING', 'Layer 1', 'III. PPE', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 1, 'มาตรฐานที่กำหนด รองเท้า, แว่นตา,หมวกนิรภัย', 55);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('STAMPING', 'Layer 1', 'III. PPE', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 2, 'สวมถุงมือกันสารเคมี, ถุงมือกันความร้อน,ถุงมือกันบาด', 56);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('STAMPING', 'Layer 1', 'III. PPE', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 3, 'สวมอุปกรณ์ป้องกันการหายใจ เช่นหน้ากากป้องกันฝุ่น  หรือไอสารเคมี', 57);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('STAMPING', 'Layer 1', 'III. PPE', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 4, 'สวมถุงมือยางเมื่อทำการล้างชิ้นส่วน,Material', 58);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('STAMPING', 'Layer 1', 'III. PPE', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 5, 'สวมถุงมือผ้าเมื่อทำการ Set up Die,Material', 59);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('STAMPING', 'Layer 1', 'III. PPE', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 6, 'สวม Ear Plug หรือ Ear Muff ทุกครั้งเมื่อเครื่องจักรทำงานเสียงดัง', 60);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('TOOL', 'Layer 3', 'SBOP (Systems Audit) Layer#3', '', 'Check', 1, 'การตรวจสอบในเรื่อง SBOP ของ Layer 2 ได้มีการดำเนินการแก้ไขอย่างถูกต้องและปัญหาที่พบได้รับการแก้ไขบนบอร์ด SBOP หรือไม่?', 12);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('TOOL', 'Layer 3', 'SBOP (Systems Audit) Layer#3', '', 'Check', 2, 'Supervisor,หัวหน้ากะและหัวหน้าฝ่ายบริหารในทุกระดับได้นำเรื่อง SBOP เข้าประชุมใน GO-Meeting และเป็นไปตามแผนที่วางไว้ หรือไม่ ?', 13);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('TOOL', 'Layer 2', 'SBOP (Systems Audit) Layer#2', '', 'Check', 1, 'การตรวจสอบในเรื่อง SBOP ของ Layer 1 ได้มีการดำเนินการแก้ไขอย่างถูกต้องและปัญหาที่พบได้รับการแก้ไขบนบอร์ด SBOP หรือไม่?', 17);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('TOOL', 'Layer 2', 'SBOP (Systems Audit) Layer#2', '', 'Check', 2, 'กิจกรรมด้านความปลอดภัยได้ถูกดำเนินการและตรวจสอบตามกำหนดเวลาหรือไม่ (BBS/CM/PM).', 18);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('TOOL', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 1, 'สังเกตพนักงานเป็นเวลา 60 วินาที', 22);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('TOOL', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 1, 'การเดินปฏิบัติงาน', 23);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('TOOL', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 2, 'การเข้าออก-พื้นที่ปฏิบัติงาน', 24);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('TOOL', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 3, 'ความสนใจกับงานที่กำลังปฏิบัติ', 25);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('TOOL', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 4, 'เทคนิคท่าทางการยกของเหมาะสม/ถูกต้อง', 26);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('TOOL', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 5, 'การก้ม/การบิด/การดึง/ตำแหน่งของร่างกาย', 27);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('TOOL', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 6, 'การยศาสตร์ (เช่น ท่าทาง)', 28);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('TOOL', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'A.ท่าทางการทำงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 7, 'ไม่เร่งรีบปฏิบัติงานจนเกินไป', 29);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('TOOL', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 1, 'มีความตระหนักถึงพื้นผิวร้อน', 31);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('TOOL', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 2, 'มีความตระหนักถึงจุดเคลื่อนไหวและส่วนหมุน', 32);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('TOOL', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 3, 'มีความตระหนักถึงจุดหนีบ', 33);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('TOOL', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 4, 'มีความตระหนักถึงวัตถุแหลมคมหรือบาด', 34);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('TOOL', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 5, 'มีความตระหนักถึงอันตรายไฟฟ้า', 35);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('TOOL', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 6, 'มีความตระหนักถึงระบบ Interlock/ปุ่มฉุกเฉิน', 36);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('TOOL', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'B. การตระหนักของพนักงาน', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 7, 'มีความตระหนักถึงการใช้อุปกรณ์ตามมาตรฐาน', 37);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('TOOL', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 1, 'ใช้เครื่องมือถูกประเภทกับงาน', 39);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('TOOL', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 2, 'เครื่องมืออยู่ในสภาพที่ยอมรับได้', 40);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('TOOL', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 3, 'ใช้สวิตซ์มือหรือเท้าถูกต้องตามมาตรฐาน', 41);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('TOOL', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 4, 'การ์ดของเครื่องจักรหรืออุปกรณ์ต่างๆ ขณะทำงานอยู่ในตำแหน่งปลอดภัย', 42);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('TOOL', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 5, 'ไม่มีการรั่วไหลของลม', 43);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('TOOL', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 6, 'สายไฟอยู่ในสภาพปลอดภัยไม่ชารุดหรือเสียหาย', 44);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('TOOL', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 7, 'ใช้อุปกรณ์ล็อค และติดป้ายเตือน (LOTO)', 45);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('TOOL', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 8, 'ปิดการ์ดเครื่องจักรทุกครั้งที่ใช้เครื่องจักร', 46);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('TOOL', 'Layer 1', 'I. ความเสี่ยงด้านความปลอดภัย - การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', '1.  สังเกตพนักงานเป็นเวลา 60 วินาที', 9, 'Airgun ตรงตามมาตรฐาน และสภาพพร้อมใช้งานไม่ชำรุด', 47);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('TOOL', 'Layer 1', 'II. สภาพแวดล้อมการทำงาน -  การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 1, 'พื้นที่ปฏิบัติงานไม่มีของวางบนพื้น (5S+1)', 49);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('TOOL', 'Layer 1', 'II. สภาพแวดล้อมการทำงาน -  การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 2, 'การกำจัดของเสียคัดแยกถูกประเภท (5S+1)', 50);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('TOOL', 'Layer 1', 'II. สภาพแวดล้อมการทำงาน -  การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 3, 'ทางเดินเปิดโล่งไม่สิ่งของกีดขวาง (5S+1)', 51);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('TOOL', 'Layer 1', 'II. สภาพแวดล้อมการทำงาน -  การดำเนินการ', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 4, 'ทางหนีไฟไม่มีสิ่งของวาง ขัดขวางการอพยพ', 52);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('TOOL', 'Layer 1', 'III. PPE', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 1, 'มาตรฐานที่กำหนด รองเท้า, แว่นตา,หมวกนิรภัย', 53);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('TOOL', 'Layer 1', 'III. PPE', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 2, 'สวมถุงมือกันสารเคมี, ถุงมือกันความร้อน,ถุงมือกันบาด', 54);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('TOOL', 'Layer 1', 'III. PPE', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 3, 'สวมอุปกรณ์ป้องกันการหายใจ เช่นหน้ากากป้องกันฝุ่น  หรือไอสารเคมี', 55);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('TOOL', 'Layer 1', 'III. PPE', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 4, 'สวมใส่อุปกรณ์ป้องกันเสียงดัง', 56);
INSERT INTO checklist_templates (department_code, layer, category, subcategory, method, item_order, question_th, row_in_excel) VALUES ('TOOL', 'Layer 1', 'IIII.  High risk process', 'C. การใช้เครื่องมือและสภาพของเครื่องมือ', 'สังเกตและตรวจสอบ', 1, 'ระบบ interlock ทำงานได้ปกติ และหินเจียรหยุดก่อนเปิดการ์ดหรือไม่', 58);

INSERT INTO system_settings (key, value, description) VALUES ('R2_PUBLIC_URL', 'https://bfdba11ba88cafd6f064809c2fe29b99.r2.cloudflarestorage.com/r2sbop', 'Cloudflare R2 Bucket Public URL');
INSERT INTO system_settings (key, value, description) VALUES ('D1_DATABASE_ID', '413b2fe9-b280-4a1b-81ac-cb20f9e41935', 'Cloudflare D1 Database ID');
