UPDATE checklist_templates SET question_en = 'Has Layer 2 SBOP verification been executed properly, and have identified defects been corrected on the SBOP board?' WHERE question_th = 'การตรวจสอบในเรื่อง SBOP ของ Layer 2 ได้มีการดำเนินการแก้ไขอย่างถูกต้องและปัญหาที่พบได้รับการแก้ไขบนบอร์ด SBOP หรือไม่?';
UPDATE checklist_templates SET question_en = 'Have Supervisors, Shift Leaders, and Management brought SBOP items into GO-Meetings according to schedule?' WHERE question_th = 'Supervisor,หัวหน้ากะและหัวหน้าฝ่ายบริหารในทุกระดับได้นำเรื่อง SBOP เข้าประชุมใน GO-Meeting และเป็นไปตามแผนที่วางไว้ หรือไม่ ?';
UPDATE checklist_templates SET question_en = 'Has Layer 1 SBOP verification been conducted correctly, and have identified issues been resolved on the SBOP board?' WHERE question_th = 'การตรวจสอบในเรื่อง SBOP ของ Layer 1 ได้มีการดำเนินการแก้ไขอย่างถูกต้องและปัญหาที่พบได้รับการแก้ไขบนบอร์ด SBOP หรือไม่?';
UPDATE checklist_templates SET question_en = 'Have safety activities been performed and audited on schedule (BBS/CM/PM)?' WHERE question_th = 'กิจกรรมด้านความปลอดภัยได้ถูกดำเนินการและตรวจสอบตามกำหนดเวลาหรือไม่ (BBS/CM/PM).';
UPDATE checklist_templates SET question_en = 'Observe employee for 60 seconds' WHERE question_th = 'สังเกตพนักงานเป็นเวลา 60 วินาที';
UPDATE checklist_templates SET question_en = 'Walking and moving while working' WHERE question_th = 'การเดินปฎิบัติงาน';
UPDATE checklist_templates SET question_en = 'Walking and moving while working' WHERE question_th = 'การเดินปฏิบัติงาน';
UPDATE checklist_templates SET question_en = 'Entering and exiting work areas' WHERE question_th = 'การเข้าออก-พื้นที่ปฏิบัติงาน';
UPDATE checklist_templates SET question_en = 'Focus and attention on the ongoing task' WHERE question_th = 'ความสนใจกับงานที่กำลังปฏิบัติ';
UPDATE checklist_templates SET question_en = 'Proper manual lifting techniques and ergonomic posture' WHERE question_th = 'เทคนิคท่าทางการยกของเหมาะสม/ถูกต้อง';
UPDATE checklist_templates SET question_en = 'Bending, twisting, pulling, and body positioning' WHERE question_th = 'การก้ม/การบิด/การดึง/ตำแหน่งของร่างกาย';
UPDATE checklist_templates SET question_en = 'Ergonomics (e.g., posture and repetitive strain)' WHERE question_th = 'การยศาสตร์ (เช่น ท่าทาง)';
UPDATE checklist_templates SET question_en = 'Working at a safe pace without excessive rushing' WHERE question_th = 'ไม่เร่งรีบปฏิบัติงานจนเกินไป';
UPDATE checklist_templates SET question_en = 'Awareness of hot surfaces and thermal hazards' WHERE question_th = 'มีความตระหนักถึงพื้นผิวร้อน';
UPDATE checklist_templates SET question_en = 'Awareness of moving parts and rotating equipment' WHERE question_th = 'มีความตระหนักถึงจุดเคลื่อนไหวและส่วนหมุน';
UPDATE checklist_templates SET question_en = 'Awareness of pinch points and nip hazards' WHERE question_th = 'มีความตระหนักถึงจุดหนีบ';
UPDATE checklist_templates SET question_en = 'Awareness of sharp edges and cut hazards' WHERE question_th = 'มีความตระหนักถึงวัตถุแหลมคมหรือบาด';
UPDATE checklist_templates SET question_en = 'Awareness of electrical hazards' WHERE question_th = 'มีความตระหนักถึงอันตรายไฟฟ้า';
UPDATE checklist_templates SET question_en = 'Awareness of safety interlocks and emergency stop buttons' WHERE question_th = 'มีความตระหนักถึงระบบ Interlock/ปุ่มฉุกเฉิน';
UPDATE checklist_templates SET question_en = 'Awareness of standard operating procedures for tools and equipment' WHERE question_th = 'มีความตระหนักถึงการใช้อุปกรณ์ตามมาตรฐาน';
UPDATE checklist_templates SET question_en = 'Awareness of correct and safe mold transfer procedures' WHERE question_th = 'มีความตระหนักถึงขั้นตอนการขนย้ายโมลอย่างถูกต้องและปลอดภัย';
UPDATE checklist_templates SET question_en = 'Using the correct type of tool for the job' WHERE question_th = 'ใช้เครื่องมือถูกประเภทกับงาน';
UPDATE checklist_templates SET question_en = 'Tools are in acceptable, serviceable condition' WHERE question_th = 'เครื่องมืออยู่ในสภาพที่ยอมรับได้';
UPDATE checklist_templates SET question_en = 'Operating hand or foot switches in accordance with safety standards' WHERE question_th = 'ใช้สวิตซ์มือหรือเท้าถูกต้องตามมาตรฐาน';
UPDATE checklist_templates SET question_en = 'Machine guards and protective covers are positioned safely during operation' WHERE question_th = 'การ์ดของเครื่องจักรหรืออุปกรณ์ต่างๆ ขณะทำงานอยู่ในตำแหน่งปลอดภัย';
UPDATE checklist_templates SET question_en = 'No compressed air leakage' WHERE question_th = 'ไม่มีการรั่วไหลของลม';
UPDATE checklist_templates SET question_en = 'Electrical cables are in safe condition without wear, chafing, or damage' WHERE question_th = 'สายไฟอยู่ในสภาพปลอดภัยไม่ชารุดหรือเสียหาย';
UPDATE checklist_templates SET question_en = 'Lockout/Tagout (LOTO) devices applied and signs posted properly' WHERE question_th = 'ใช้อุปกรณ์ล็อค และติดป้ายเตือน (LOTO)';
UPDATE checklist_templates SET question_en = 'Verify TCU hoses and fittings are properly connected before operation' WHERE question_th = 'ตรวจสอบความถูกต้องของท่อ TCU และ ข้อต่อก่อนทำงาน';
UPDATE checklist_templates SET question_en = 'Air blow gun complies with safety standards and is undamaged' WHERE question_th = 'Airgun ตรงตามมาตรฐาน และสภาพพร้อมใช้งานไม่ชำรุด';
UPDATE checklist_templates SET question_en = 'Electric Stacker or Powered Hand Pallet inspected and in ready-to-use condition' WHERE question_th = 'รถ  Electric Stacker หรือ Powered Hand Pallet มีการตรวจเช็ค สภาพพร้อมใช้งาน';
UPDATE checklist_templates SET question_en = 'Stitching/stapling machine in complete, operable condition' WHERE question_th = 'เครื่องเย็บมีสภาพสมบูรณ์ พร้อมใช้งาน';
UPDATE checklist_templates SET question_en = 'Carts and trolleys in good condition and parked in designated areas, not leaning on machinery' WHERE question_th = 'รถเข็น มีสภาพสมบูรณ์ และจัดเก็บในพื้นที่ที่กำหนด ไม่วางพิงกับเรื่องจักร หรืออุปกรณ์อื่นๆ';
UPDATE checklist_templates SET question_en = 'Workplace floor clear of loose objects and clutter (5S+1)' WHERE question_th = 'พื้นที่ปฏิบัติงานไม่มีของวางบนพื้น (5S+1)';
UPDATE checklist_templates SET question_en = 'Waste segregated into correct categories for disposal (5S+1)' WHERE question_th = 'การกำจัดของเสียคัดแยกถูกประเภท (5S+1)';
UPDATE checklist_templates SET question_en = 'Walkways clear of obstacles and trip hazards (5S+1)' WHERE question_th = 'ทางเดินเปิดโล่งไม่สิ่งของกีดขวาง (5S+1)';
UPDATE checklist_templates SET question_en = 'Emergency exits and evacuation routes free of obstructions' WHERE question_th = 'ทางหนีไฟไม่มีสิ่งของวาง ขัดขวางการอพยพ';
UPDATE checklist_templates SET question_en = 'Fire safety equipment unobstructed and accessible in emergencies' WHERE question_th = 'อุปกรณ์ป้องกันอัคคีภัย ไม่มีสิ่งของวางสามารถเข้าถึงได้กรณีเกิดเหตุฉุกเฉิน';
UPDATE checklist_templates SET question_en = 'Standard mandatory PPE: Safety shoes, safety glasses, and hard hat' WHERE question_th = 'มาตรฐานที่กำหนด รองเท้า, แว่นตา,หมวกนิรภัย';
UPDATE checklist_templates SET question_en = 'Wear chemical-resistant, heat-resistant, or cut-resistant gloves as required' WHERE question_th = 'สวมถุงมือกันสารเคมี, ถุงมือกันความร้อน,ถุงมือกันบาด';
UPDATE checklist_templates SET question_en = 'Wear respiratory protection such as dust mask or chemical vapor respirator' WHERE question_th = 'สวมอุปกรณ์ป้องกันการหายใจ เช่นหน้ากากป้องกันฝุ่น  หรือไอสารเคมี';
UPDATE checklist_templates SET question_en = 'Wear appropriate PPE when working with molten plastic at mold faces and nozzle areas' WHERE question_th = 'สวมอุปกรณ์ PPE สำหรับขั้นตอน การทำงานกับพลาสติกเหลวร้อน ทั้งหน้าแม่พิมพ์ และ บริเวณ Nozzle';
UPDATE checklist_templates SET question_en = 'Are safety plate locking clamps utilized during mold repair/maintenance?' WHERE question_th = 'มีการใช้ แคลมป์ล๊อค plate ขณะซ่อมแม่พิมพ์หรือไม่';
UPDATE checklist_templates SET question_en = 'Does the mold lifting hook have a safety latch/cover and is it in ready condition?' WHERE question_th = 'ตะขอเกี่ยวแม่พิมพ์มี cover และอยู่ในสภาพพร้อมใช้งานหรือไม่';
UPDATE checklist_templates SET question_en = 'Are parts blown dry inside the enclosure after ultrasonic cleaning?' WHERE question_th = 'เป่าชิ้นงานภายในตู้หลังจากล้างที่เครื่อง ultrasonic หรือไม่';
UPDATE checklist_templates SET question_en = 'Is the argon gas leak detector functioning normally?' WHERE question_th = 'เครื่องตรวจจับก๊าซอาร์กอนรั่ว ทำงานปกติหรือไม่';
UPDATE checklist_templates SET question_en = 'Do not use 1.2-ton Jumbo Electric Stacker to transport molds into machine zones' WHERE question_th = 'ไม่ใช้ Electric Stacker (Jumbo) ขนาด 1.2 ตัน ขนย้ายโมลเข้ามายังพื้นที่ในโซนเครื่องจักร';
UPDATE checklist_templates SET question_en = 'Machine guarding in serviceable condition, free of cracks or damage' WHERE question_th = 'การ์ดของเครื่องจักรอยู่ในสภาพพร้อมใช้งาน ไม่แตกหรือชำรุด';
UPDATE checklist_templates SET question_en = 'Wear protective gloves and ear muffs while operating cold jet' WHERE question_th = 'สวมถุงมือ และ Ear Muff ขณะใช้ cold jet';
UPDATE checklist_templates SET question_en = 'Awareness of proper waste segregation guidelines' WHERE question_th = 'มีความตระหนักถึงการคัดแยกขยะที่ถูกต้อง';
UPDATE checklist_templates SET question_en = 'Ensure machine safety doors/guards are closed upon completion of Repair or PM' WHERE question_th = 'ปิดการ์ดเครื่องจักรทุกครั้งที่มีการ Repair หรือ PM';
UPDATE checklist_templates SET question_en = 'Ladders inspected before use and in safe operable condition' WHERE question_th = 'บันไดสภาพพร้อมใช้งาน และมีการตรวจเช็คก่อนใช้งาน';
UPDATE checklist_templates SET question_en = 'Fire fighting equipment clear and accessible in emergencies' WHERE question_th = 'อุปกรณ์ป้องกันอัคคีภัย ไม่มีสิ่งของกีดขวางสามารถเข้าถึงได้กรณีเกิดเหตุฉุกเฉิน';
UPDATE checklist_templates SET question_en = 'Contractors trained and certified for working at heights (when applicable)' WHERE question_th = 'ผู้รับเหมาผ่านการอบรม พร้อมสำหรับทำงานบนที่สูง (กรณีมีผู้รับเหมาปฏิบัติงาน)';
UPDATE checklist_templates SET question_en = 'Fall protection equipment inspected and properly worn when working at heights' WHERE question_th = 'ใช้อุปกรณ์กันตกสำหรับงานที่สูง และสภาพพร้อมใช้งาน';
UPDATE checklist_templates SET question_en = 'Fire safety equipment in the area unobstructed' WHERE question_th = 'อุปกรณ์ป้องกันอัคคีภัยภายในพื้นที่ ไม่มีสิ่งของกีดขวาง';
UPDATE checklist_templates SET question_en = 'Standard mandatory PPE: Safety shoes and safety glasses' WHERE question_th = 'มาตรฐานที่กำหนด รองเท้า, แว่นตา';
UPDATE checklist_templates SET question_en = 'Awareness of overhead hazards and falling objects' WHERE question_th = 'มีความตระหนักถึงอันตรายจากสิ่งของตกจากที่สูง';
UPDATE checklist_templates SET question_en = 'Awareness of forklift driving safety regulations' WHERE question_th = 'มีความตระหนักถึงความปลอดภัยในการขับขี่ Fork lift';
UPDATE checklist_templates SET question_en = 'Pallets in sound condition without cracks, splits, or structural damage' WHERE question_th = 'พาเลทสภาพพร้อมใช้งาน ไม่แตกชำรุด';
UPDATE checklist_templates SET question_en = 'Forklift inspected prior to use and ignition key removed after operation' WHERE question_th = 'Fork lift สภาพพร้อมใช้งาน มีการตรวจเช็คก่อนใช้งาน ถอดกุญแจทุกครั้งหลังจากการใช้งาน';
UPDATE checklist_templates SET question_en = 'Wear hard hat when working inside racking zones' WHERE question_th = 'สวมหมวกแข็งเมื่อปฏิบัติงานอยู่ในพื้นที่ในRack';
UPDATE checklist_templates SET question_en = 'Wear cloth gloves whenever cutting stainless steel strapping bands' WHERE question_th = 'สวมถุงมือผ้าทุกครั้งที่มีการตัดสายรัดสแตนเลส';
UPDATE checklist_templates SET question_en = 'Do not drive high-mast Forklift (S/N MHB4279H) into control room areas' WHERE question_th = 'ไม่นำรถ Fork Lift เสากระโดงงาสูง Serial number MHB4279H เข้าไปยังพื้นที่ห้องควบคุม';
UPDATE checklist_templates SET question_en = 'Set maximum lift height limit for forklift mast according to high-rack retrieval standards' WHERE question_th = 'Set limit max การยกงาของรถโฟรค์ลิฟ กำหนดมาตรฐานการตักงานจากที่สูง';
UPDATE checklist_templates SET question_en = 'Tensile tester guard in place and engaged prior to test execution' WHERE question_th = 'ครื่องวัดแรงดึงมีการใช้การ์ดก่อนการทดสอบ';
UPDATE checklist_templates SET question_en = 'Guards or safety fixtures utilized during cutting operations' WHERE question_th = 'มีการใช้การ์ดหรืออุปกรณ์ป้องกันในการตัด';
UPDATE checklist_templates SET question_en = 'Awareness of proper hand pallet truck and lifter operation' WHERE question_th = 'มีความตระหนักถึงการใช้ Hand lift,Lifter';
UPDATE checklist_templates SET question_en = 'Cutting tools and shears in ready and safe condition' WHERE question_th = 'เครื่องมือสำหรับตัด,กรรไกร สภาพพร้อมใช้งาน';
UPDATE checklist_templates SET question_en = 'Hand pallet truck and lifter intact, undamaged, and always ready for use' WHERE question_th = 'Hand lift,Lifter ไม่ชำรุดพร้อมใช้งานอยู่เสมอ';
UPDATE checklist_templates SET question_en = 'Electric Stacker in good condition and key removed after use' WHERE question_th = 'Electric Stacker สภาพพร้อมใช้งาน ถอดกุญแจทุกครั้งหลังจากการใช้งาน';
UPDATE checklist_templates SET question_en = 'Wear rubber gloves when cleaning parts and raw materials' WHERE question_th = 'สวมถุงมือยางเมื่อทำการล้างชิ้นส่วน,Material';
UPDATE checklist_templates SET question_en = 'Wear cloth gloves during die setup and material handling' WHERE question_th = 'สวมถุงมือผ้าเมื่อทำการ Set up Die,Material';
UPDATE checklist_templates SET question_en = 'Wear ear plugs or ear muffs whenever operating in high-noise areas' WHERE question_th = 'สวม Ear Plug หรือ Ear Muff ทุกครั้งเมื่อเครื่องจักรทำงานเสียงดัง';
UPDATE checklist_templates SET question_en = 'Always keep machine guards closed during machine operation' WHERE question_th = 'ปิดการ์ดเครื่องจักรทุกครั้งที่ใช้เครื่องจักร';
UPDATE checklist_templates SET question_en = 'Wear hearing protection equipment' WHERE question_th = 'สวมใส่อุปกรณ์ป้องกันเสียงดัง';
UPDATE checklist_templates SET question_en = 'Does the safety interlock function properly and grinding wheel stop before opening guard?' WHERE question_th = 'ระบบ interlock ทำงานได้ปกติ และหินเจียรหยุดก่อนเปิดการ์ดหรือไม่';
